top_search_terms = [
    "weather today",
    "green bay packers",
    "restaurants near me",
    "stock market update",
    "grand theft auto 6 news",
    "concert near me",
    "toronto raptors score",
    "event in toronto",
    "stock market HOG",
    "directions to skydome",
    "meaning of word automation",
    "what time is it PST",
    "shopping jacket",
    "lyrics flowers",
    "dune movie",
    "translate robot English to French",
    "Spotify",
    "eBay",
    "Wikipedia",
    "Yahoo",
    "Outlook",
    "Craigslist",
    "CNN",
    "BBC",
    "ESPN",
    "Hulu",
    "Disney Plus",
    "PayPal",
    "Uber",
    "Convert 100 CAD to USD"
]